services:
  caddy:
    image: iarekylew00t/caddy-cloudflare:latest
    container_name: caddy
    hostname: caddy
    restart: unless-stopped
    env_file: .env
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy-config:/config
      - ./caddy-data:/data
      - /data/:/mnt/data

networks:
  default:
    name: $DOCKER_MY_NETWORK
    external: true
