services:
  homarr:
    image: ghcr.io/homarr-labs/homarr:latest
    container_name: homarr
    restart: unless-stopped
    env_file: .env
    environment:
      - SECRET_ENCRYPTION_KEY=${HOMARR_SECRET_ENCRYPTION_KEY}
    volumes:
      - /run/user/1000/docker.sock:/var/run/docker.sock
      - ./homarr/appdata:/appdata
    expose:
      - "7575"

networks:
  default:
    name: $DOCKER_MY_NETWORK
    external: true
