services:
  rarbg:
    image: ghcr.io/mgdigital/rarbg-selfhosted:latest
    container_name: rarbg
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./rarbg_db.sqlite:/rarbg_db.sqlite
      - ./trackers.txt:/trackers.txt
    ports:
      - 3333:3333

networks:
  default:
    name: $DOCKER_MY_NETWORK
    external: true
