services:
  slskd:
    image: slskd/slskd
    container_name: slskd
    restart: always
    env_file: .env
    environment:
      - SLSKD_REMOTE_CONFIGURATION=true
    volumes:
      - ./slskd-appdata:/app
      - /data/media/:/data/media/
    expose:
      - "5030"
      - "5031"
    ports:
      - 50300:50300

networks:
  default:
    name: $DOCKER_MY_NETWORK
    external: true
